### ISSUE TITLE
Link to quick reference guide broken

### ISSUE THREAD

**Issue by hectorsector** [githubtraining/uploading-your-local-project#19]
## Bug Report

**Current behavior**
In [`responses/00_make-a-plan.md`](https://github.com/githubtraining/uploading-your-local-project/blob/master/responses/00_make-a-plan.md#keyboard-activity-exporting-your-project), there's a broken link to a quick reference guide.

**Reproduction**
Steps to reproduce the behavior in the course:
1. Register for this course.
1. Try and click on the quick reference guide referenced in the first issue. 

**Expected behavior**
The target guide should either become available or the link should be removed. 

**Possible solution**
I don't think we have the quick reference guide any more (or it may be outdated at this point) so the best course of action might be to remove it. 

**Additional context**
Reported by @klickerlebnis in the [community forum](https://github.community/t5/GitHub-Learning-Lab/quot-Quick-Reference-Guide-quot-not-available-for-course-quot/m-p/58726#M1408)

**Comment by hectorsector** [comment]
Another [report](https://github.community/t/link-broken-in-github-upload-course/118008) from the forum.

**Comment by vaghelabhavesh** [comment]
@hectorsector Thanks for fixing this.
