### ISSUE TITLE
Https repository links give problems with 2FA  

### ISSUE THREAD

**Issue by bjbuter** [githubtraining/uploading-your-local-project#20]
## Bug Report

**Current behavior**
In [responses/02_move-local.md](https://github.com/githubtraining/uploading-your-local-project/blob/master/responses/02_move-local.md) {{ repoUrl }}.git is used to generate https links to the git repository. Https gave me problems when 2FA is already enabled.

**Reproduction**
Steps to reproduce the behavior in the course:
1. Enable 2FA
2. Start the course and arrive at 02_move-local.md
3. Use the provided links for instance in use command line: Type git remote add origin {{ repoUrl }}.git
4. Use your username and password. 
5. Response: `remote: Invalid username or password.`

**Expected behavior**
I expect a way to avoid or resolve this problem in the course documentation.

**Possible solution**
Instead of only providing the {{ repoUrl }} also provide a SSH access method. This would have worked for me, but I already had my ssh-key based access enabled. 
Otherwise, provide an option to self-diagnose and switch to a different access method. 

**Additional context**
I understand that this is expected behaviour when 2FA is enabled and no personal access token is used. However, for a novice that has to have 2FA enabled because of an organisational policy, this is a step that they might get stuck.

**Comment by davenowell** [comment]
@bjbuter Thank you for reporting this.  We are looking into the behavior and taking the necessary steps.
