### ISSUE TITLE
Misspelled word in course-details.md

### ISSUE THREAD

**Issue by christyc01** [githubtraining/uploading-your-local-project#27]
## Bug Report

**Current behavior**
In course-details.md, one instance of "to" should be changed to "do".

**Reproduction**
Steps to reproduce the behavior in the course:
1. Go to the 'What you'll learn' section in course-details.md
2. The third bullet from the bottom of that section contains the error ("How **to** I move my existing project to GitHub?")

**Expected behavior**
Change "to" to "do" (should be "How **do** I move my existing project to GitHub?").

**Screenshot**
<img width="376" alt="course-details edit" src="https://user-images.githubusercontent.com/57055910/109113988-49fab200-76fa-11eb-8cde-a001c0ad9236.png">

**Comment by chandrakishorSingh** [comment]
I have opened a pull request #30 for this. Can you review it @brianamarie ?

**Comment by brianamarie** [comment]
Fixed by #30. Thank you, @chandrakishorSingh!
